### ISSUE TITLE
Activating the projector crashes when using alongside the mod Cubic Chunks

### ISSUE THREAD

**Issue by steampunko** [iChun/GeneralLaymansAestheticSpyingScreen#7]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.781.0.jar)
  CoreModLoader (Sound-Physics-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/22/17 8:56 PM
Description: Rendering Block Entity

java.lang.ArrayIndexOutOfBoundsException: -2
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.world.RenderGlobalProxy.renderEntities(RenderGlobalProxy.java:321)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.drawWorld(WorldPortalRenderer.java:466)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.drawWorld(WorldPortalRenderer.java:202)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.renderWorldPortal(WorldPortalRenderer.java:127)
	at me.ichun.mods.glass.client.render.TileEntityGlassRenderer.drawScene(TileEntityGlassRenderer.java:169)
	at me.ichun.mods.glass.client.render.TileEntityGlassRenderer.render(TileEntityGlassRenderer.java:105)
	at me.ichun.mods.glass.client.render.TileEntityGlassRenderer.func_192841_a(TileEntityGlassRenderer.java:28)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1033)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1377)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.world.RenderGlobalProxy.renderEntities(RenderGlobalProxy.java:321)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.drawWorld(WorldPortalRenderer.java:466)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.drawWorld(WorldPortalRenderer.java:202)
	at me.ichun.mods.ichunutil.common.module.worldportals.client.render.WorldPortalRenderer.renderWorldPortal(WorldPortalRenderer.java:127)
	at me.ichun.mods.glass.client.render.TileEntityGlassRenderer.drawScene(TileEntityGlassRenderer.java:169)
	at me.ichun.mods.glass.client.render.TileEntityGlassRenderer.render(TileEntityGlassRenderer.java:105)
	at me.ichun.mods.glass.client.render.TileEntityGlassRenderer.func_192841_a(TileEntityGlassRenderer.java:28)

-- Block Entity Details --
Details:
	Name: minecraft:glass_temaster // me.ichun.mods.glass.common.tileentity.TileEntityGlassMaster
	Block type: ID #254 (tile.glass.block.glass // me.ichun.mods.glass.common.block.BlockGlass)
	Block data value: 1 / 0x1 / 0b0001
	Block location: World: (9,4,12), Chunk: (at 9,0,12 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #254 (tile.glass.block.glass // me.ichun.mods.glass.common.block.BlockGlass)
	Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:197)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:153)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1033)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1781)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1606)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Jarfeh'/671, l='MpServer', x=9.55, y=4.00, z=9.00]]
	Chunk stats: MultiplayerChunkCache: 15607/625
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,4,8), Chunk: (at 8,0,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 350 game time, 350 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityLatchedRenderer['unknown'/814, l='MpServer', x=9.55, y=4.00, z=9.00], EntityPlayerSP['Jarfeh'/671, l='MpServer', x=9.55, y=4.00, z=9.00]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3263686528 bytes (3112 MB) / 4281597952 bytes (4083 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 7 total; -Xms4G -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C7 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State          | ID                                  | Version          | Source                                               | Signature                                |
	|:-------------- |:----------------------------------- |:---------------- |:---------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAAAAAAA | minecraft                           | 1.12.2           | minecraft.jar                                        | None                                     |
	| UCHIJAAAAAAAAA | mcp                                 | 9.42             | minecraft.jar                                        | None                                     |
	| UCHIJAAAAAAAAA | FML                                 | 8.0.99.99        | forge-1.12.2-14.23.1.2555.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | forge                               | 14.23.1.2555     | forge-1.12.2-14.23.1.2555.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAAAAAAA | cubicchunks                         | 1.12.2-0.0.781.0 | CubicChunks-1.12.2-0.0.781.0.jar                     | None                                     |
	| UCHIJAAAAAAAAA | ichunutil                           | 7.1.4            | iChunUtil-1.12.2-7.1.4.jar                           | None                                     |
	| UCHIJAAAAAAAAA | generallaymansaestheticspyingscreen | 7.0.0            | GeneralLaymansAestheticSpyingScreen-1.12.2-7.0.0.jar | None                                     |
	| UCHIJAAAAAAAAA | mineshot                            | v1.71-1.12       | Mineshot-v1.71-1.12.jar                              | None                                     |
	| UCHIJAAAAAAAAA | soundphysics                        | 1.0.4            | Sound-Physics-1.12.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.781.0.jar)
  
CoreModLoader (Sound-Physics-1.12.2.jar)
  com.sonicether.soundphysics.CoreModInjector
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 385.69' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.1.2555
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.5.0 NVIDIA 385.69, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Default Improved 1.12.zip, SE-Soundfix-v0.2.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz

**Comment by MrLightningBlaze** [comment]
It is able to launch and run just fine with me with the latest version as of now (7.0.0), however, it does not actually render any blocks, only some particles and entities, and the rest is just the skybox

**Comment by pawelk1337** [comment]
CubicChunks is glichi
